CLASS zz1_cl_fixedasset DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zz1_i_fixedasset.
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZZ1_CL_FIXEDASSET IMPLEMENTATION.
ENDCLASS.
